### ISSUE TITLE
Redux DevTools vNext Umbrella

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#130]
- [x] Move LogMonitor into a separate project (#132)
- [x] Kill <DevTools> and provide a simpler API to connect monitors (#132)
- [x] Perf improvements
- [x] Kill DebugPanel in favor of docking solution with persistence (https://github.com/gaearon/redux-devtools/pull/107, #132)
- [ ] Provide a built-in helper for opening DevTools in a separate window
- [ ] Update docs and examples

**Comment by iamdustan** [comment]
>  Provide a built-in helper for opening DevTools in a separate window

I’m using `react-popover` in a project right now and it works out of the box. My current implementation is fairly standard. Current state of the DevTools UI is within the component itself and it takes your actual app as children: https://gist.github.com/iamdustan/c5867aa3d0a40ff0ecf1

<img width="132" alt="Icons docked to the bottom right of the viewport" src="https://cloud.githubusercontent.com/assets/227879/10195326/0f20f112-675b-11e5-9139-8d5f43983133.png">

<img width="510" alt="In a popover" src="https://cloud.githubusercontent.com/assets/227879/10195365/3d41373c-675b-11e5-8765-8342bac296a9.png">

Usage is:

```
const app = <Provider ... /><Routes ... /></Provider>;
ReactDOM.render(
  process.env.NODE_ENV === 'production' ? app :
  <Devtools store={store}>{app}</Devtools>
), element);
```

**Comment by iamdustan** [comment]
Ah. Just saw https://github.com/gaearon/redux-devtools/pull/132. Looking forward to that new world!

**Comment by ohana54** [comment]
@gaearon any plans to support AMD?

**Comment by gaearon** [comment]
@ohana54 

What would supporting it involve? Webpack already supports AMD out of the box so you shouldn't need anything special. In any case, I'd encourage you not to write new code in AMD as it's a format of the past.

**Comment by ohana54** [comment]
My knowledge is limited on the subject, but I tried using the npm module and it doesn't look like a webpack output. I also saw in package.json that the only build step is running babel. I'm sorry if I'm completely off here.

**Comment by ohana54** [comment]
Forgot to mention, using AMD is last thing in the world I want to do right now, unfortunately don't have a choice.

**Comment by gaearon** [comment]
>My knowledge is limited on the subject, but I tried using the npm module and it doesn't look like a webpack output. I also saw in package.json that the only build step is running babel. I'm sorry if I'm completely off here.

The NPM module is in CommonJS. Webpack lets you mix AMD and CommonJS code in one project so it shouldn't be an issue if you're using Webpack.

We don't plan to provide an AMD build of Redux DevTools, just like there's no AMD build of Redux itself.

**Comment by gaearon** [comment]
In any case, this if off topic to this thread. Please file a new issue if you'd like to discuss this further.

**Comment by ohana54** [comment]
Sure, opened #139
